name: Build Server

on:
  workflow_dispatch:
  push:
    paths: [ "src/**", ".github/workflows/la-minute-referendum.yml" ]
    branches: [ main ]    
  pull_request:
    paths: [ "src/**", ".github/workflows/la-minute-referendum.yml" ]
    branches: [ main ]    
permissions:
  contents: write

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-server:
    runs-on: ubuntu-latest
    name: la-minute-referendum build
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: preview

    - name: Build server
      working-directory: src/LaMinuteReferendum
      run: dotnet publish -c Release -o publishout
